CLASS zcl_sw_class_in_test_i517012 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_sw_class_in_test_i517012 IMPLEMENTATION.
ENDCLASS.
