CLASS zcl_sw_abapgit_test DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  "Dummy Class Changes from local 4
ENDCLASS.



CLASS zcl_sw_abapgit_test IMPLEMENTATION.
ENDCLASS.
